// brain_health.test.ts — the pure core behind `amico brain-health` (amicode
// #1687, brain flywheel slice 8 — the brain measures itself): the receipt
// parser over the notturno journal's own bytes, the five KPI families computed
// over fixture receipts + fixture claim state, and the dated brief render.
//
// FIXTURE DISCIPLINE (the issue's Testing Decision — "fixture receipts +
// fixture claims → pinned KPI assertions"): every fixture is generated by the
// machinery that owns its format — the receipts journal through the real
// notturno_passes writer, the candidate notes through the real distill
// renderer, the review queue through the real lifecycle renderer — so the
// parser can never drift from the writers, and the pinned numbers below are
// the report's contract.
//
// The report MEASURES, never acts: no fixture substrate is ever written by
// the core, and every number carries the provenance line that produced it.
//
// Run: `pnpm --filter @amicode/amico-run test brain_health`
import { describe, it, expect } from "vitest";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { stringify as stringifyYaml } from "yaml";

import { appendSection, renderPass } from "../src/notturno_passes.js";
import { renderClaimNote as renderCandidateNote } from "../src/distill.js";
import { loadRegistryClaims } from "../src/claims.js";
import { renderQueueFile, type QueueEntry } from "../src/lifecycle.js";
import { writeDistillState, stampDistilled, type DistillState } from "../src/distill.js";
import {
  BRAIN_HEALTH_JOB,
  parsePasses,
  loadCandidateStamps,
  readReviewQueueCount,
  computeHealthReport,
  renderHealthBrief,
} from "../src/brain_health.js";

const PERIOD = "2026-10";
const CLOCK = () => new Date("2026-10-31T00:00:00.000Z");

// ── the fixture journal: 13 receipts, generated by the single writer ───────────

/** One receipt row, written through the real renderPass. */
function receipt(date: string, job: string, outcome: string, status = "ok"): string {
  return renderPass({ job, status, outcome, duration_s: 12, artifacts: [], when: new Date(`${date}T04:00:00.000Z`) });
}

function fixtureJournal(): string {
  const dir = mkdtempSync(join(tmpdir(), "brain-health-journal-"));
  const lines: string[] = [
    // September history (outside the period — the report windows on period)
    receipt(
      "2026-09-28",
      "distill",
      "distill: scanned 12 sessions (substantive 4, junk 8), distilled 4, claims 3, none 1, errors 0",
    ),
    receipt("2026-09-30", "prune", "prune: 1 fixes applied (1 unambiguous findings), 2 drift findings flagged for a human"),
    receipt(
      "2026-09-30",
      BRAIN_HEALTH_JOB,
      "brain-health: period 2026-09 — receipts 4, claims 3, created 3, applied 1, refuted 0, drift 2 — brief briefs/health-2026-09.md",
    ),
    // the period under test
    receipt("2026-10-01", "distill", "distill: scanned 30 sessions (substantive 10, junk 20), distilled 8, claims 6, none 2, errors 0"),
    receipt("2026-10-02", "distill", "distill: scanned 32 sessions (substantive 11, junk 21), distilled 3, claims 2, none 1, errors 0"),
    receipt("2026-10-07", "prune", "prune: 2 fixes applied (2 unambiguous findings), 1 drift findings flagged for a human"),
    receipt("2026-10-14", "prune", "prune: 0 fixes applied (0 unambiguous findings), 4 drift findings flagged for a human"),
    receipt(
      "2026-10-06",
      "promote",
      "promote: 3 claims proposed (bundle promote-20261006-060000), overflow 1 carried, excluded 0 — PROPOSES only, a human merges",
    ),
    receipt("2026-10-08", "synthesize", "synthesize: 2 hopper proposals, 1 already proposed (skipped), 1 patterns carried — strategy untouched"),
    receipt(
      "2026-10-05",
      "extract-meetings",
      "extract-meetings: proposed tags for meeting-2026-10-05.md (products 2, projects 1, entities 3, types 1, themes 2), 1 named gaps, proposed 2 hopper item(s)",
    ),
    receipt("2026-10-12", "extract-meetings", "extract-meetings: skipped meeting-2026-10-12.md (status tagged)"),
    receipt("2026-10-09", "triage-papers", "triage-papers: scanned 12 papers (high 3), seeded 2, no-match 4, skipped 6"),
    // a status-OK distill whose outcome left the writer's pinned shape → a named finding (writer drift)
    receipt("2026-10-03", "distill", "distill: crashed mid-pass"),
    // a FAILED pass: counted in the receipts meta (failure is a fact), excluded from every family, never a finding
    receipt("2026-10-04", "distill", "distill: jev middle layer disabled — fail-open, nothing distilled", "failed"),
  ];
  for (const section of lines) appendSection(dir, section);
  return readFileSync(join(dir, "scheduled-passes.md"), "utf8");
}

// ── the fixture registry: 5 claims with pinned history events ────────────────

function claimNote(file: string, claim: Record<string, unknown>, dir: string): void {
  writeFileSync(join(dir, file), `---\n${stringifyYaml(claim, { lineWidth: 0 }).trimEnd()}\n---\n\n# ${claim.statement}\n\nfixture claim (brain_health.test.ts).\n`);
}

function fixtureRegistry(): string {
  const dir = mkdtempSync(join(tmpdir(), "brain-health-registry-"));
  claimNote(
    "insight-applied.md",
    {
      type: "insight",
      statement: "two applied events in the period",
      status: "unverified",
      confidence: "medium",
      evidence: ["chat-session/sess-a"],
      applied: 2,
      last_applied: "2026-10-20T00:00:00.000Z",
      history: [
        { date: "2026-08-10T00:00:00.000Z", event: "projected", note: "fixture" },
        { date: "2026-10-04T00:00:00.000Z", event: "applied", note: "applied via recommend-outcome x-gate/12" },
        { date: "2026-10-20T00:00:00.000Z", event: "applied", note: "applied via recommend-outcome t-gate/3" },
      ],
      scope: "personal",
      tags: ["fixture"],
    },
    dir,
  );
  claimNote(
    "best-practice-applied.md",
    {
      type: "best-practice",
      statement: "one applied event in the period",
      status: "corroborated",
      confidence: "high",
      evidence: ["chat-session/sess-b", "memory-card/x.md", "paper/y.md"],
      applied: 1,
      last_applied: "2026-10-10T00:00:00.000Z",
      history: [
        { date: "2026-08-01T00:00:00.000Z", event: "projected", note: "fixture" },
        { date: "2026-10-10T00:00:00.000Z", event: "applied", note: "applied via solve-run r20261008" },
      ],
      scope: "team",
      tags: ["fixture"],
    },
    dir,
  );
  claimNote(
    "insight-refuted.md",
    {
      type: "insight",
      statement: "refuted in the period",
      status: "refuted",
      confidence: "medium",
      evidence: ["chat-session/sess-c"],
      applied: 0,
      last_applied: null,
      history: [
        { date: "2026-08-01T00:00:00.000Z", event: "projected", note: "fixture" },
        { date: "2026-10-03T00:00:00.000Z", event: "refuted", note: "contradicted by run r20261001 (fixture)" },
      ],
      scope: "personal",
      tags: ["fixture"],
    },
    dir,
  );
  claimNote(
    "insight-corroborated.md",
    {
      type: "insight",
      statement: "corroborated in the period",
      status: "corroborated",
      confidence: "high",
      evidence: ["chat-session/sess-d", "memory-card/e.md", "paper/f.md"],
      applied: 0,
      last_applied: null,
      history: [
        { date: "2026-08-01T00:00:00.000Z", event: "projected", note: "fixture" },
        { date: "2026-10-04T00:00:00.000Z", event: "corroborated", note: "evidence crossed the threshold (fixture)" },
      ],
      scope: "personal",
      tags: ["fixture"],
    },
    dir,
  );
  claimNote(
    "insight-stale.md",
    {
      type: "insight",
      statement: "applied only outside the period",
      status: "unverified",
      confidence: "low",
      evidence: ["chat-session/sess-e"],
      applied: 1,
      last_applied: "2026-09-20T00:00:00.000Z",
      history: [
        { date: "2026-09-15T00:00:00.000Z", event: "projected", note: "fixture" },
        { date: "2026-09-20T00:00:00.000Z", event: "applied", note: "applied via recommend-outcome old/1" },
      ],
      scope: "personal",
      tags: ["fixture"],
    },
    dir,
  );
  return dir;
}

// ── the fixture candidate area: 3 candidate notes through the real renderer ──

function fixtureCandidates(): string {
  const dir = mkdtempSync(join(tmpdir(), "brain-health-candidates-"));
  const note = (sessionId: string, updatedMs: number, distilledAt: string): string =>
    renderCandidateNote({
      sessionId,
      sessionTitle: `session ${sessionId}`,
      sessionCreatedMs: updatedMs - 86_400_000,
      sessionUpdatedMs: updatedMs,
      sourceDb: "/fixture/chat.db",
      distilledAt,
      claimType: "insight",
      confidence: 0.9,
      evidence: [{ messageId: `msg-${sessionId}`, role: "user", timeCreatedMs: updatedMs, text: "fixture evidence" }],
    });
  writeFileSync(join(dir, "claim-sess-a.md"), note("sess-a", Date.parse("2026-09-25T00:00:00.000Z"), "2026-10-01T00:00:00.000Z"));
  writeFileSync(join(dir, "claim-sess-b.md"), note("sess-b", Date.parse("2026-10-01T12:00:00.000Z"), "2026-10-02T00:00:00.000Z"));
  writeFileSync(join(dir, "claim-sess-c.md"), note("sess-c", Date.parse("2026-09-20T00:00:00.000Z"), "2026-09-28T00:00:00.000Z"));
  return dir;
}

/** The fixture review queue — rendered by the real lifecycle renderer, two entries. */
function fixtureQueue(): string {
  const path = join(mkdtempSync(join(tmpdir(), "brain-health-queue-")), "review-queue.md");
  const entry = (file: string, days: number): QueueEntry => ({
    file,
    statement: `stale claim ${file}`,
    type: "insight",
    status: "unverified",
    confidence: "low",
    applied: 0,
    last_applied: null,
    age_days: days,
    reason: `never applied — no lifecycle activity since long ago, ${days} days beyond the 90-day window`,
  });
  writeFileSync(
    path,
    renderQueueFile([entry("insight-old-a.md", 120), entry("insight-old-b.md", 150)], { now: CLOCK(), windowDays: 90 }),
  );
  return path;
}

/** The fixture distill state stamp: 9 sessions ever distilled. */
function fixtureDistillState(): number {
  let state: DistillState = { schema_version: 1, entries: {} };
  for (let i = 0; i < 9; i++) state = stampDistilled(state, `sess-${i}`, "insight", null, "2026-10-02T04:00:00.000Z");
  const path = join(mkdtempSync(join(tmpdir(), "brain-health-state-")), "distill-state.json");
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(state));
  return 9;
}

// ── parsePasses: the journal's own bytes, via the single writer ───────────────

describe("parsePasses — the notturno journal, read by its writer's shape", () => {
  it("parses every fixture section: date, job, status, outcome, duration", () => {
    const { receipts, findings } = parsePasses(fixtureJournal());
    expect(receipts.length).toBe(14);
    expect(findings).toEqual([]);
    const first = receipts.find((r) => r.date === "2026-10-01")!;
    expect(first.job).toBe("distill");
    expect(first.status).toBe("ok");
    expect(first.outcome).toBe("distill: scanned 30 sessions (substantive 10, junk 20), distilled 8, claims 6, none 2, errors 0");
    expect(first.duration_s).toBe(12);
    const failed = receipts.find((r) => r.date === "2026-10-04")!;
    expect(failed.status).toBe("failed");
  });

  it("parses a header-only journal as empty (no sections, no findings)", () => {
    const { receipts, findings } = parsePasses("# Scheduled passes\n\nOne record per pass. Nothing here yet.\n");
    expect(receipts.length).toBe(0);
    expect(findings).toEqual([]);
  });

  it("names a malformed section header, never silently drops it", () => {
    const { receipts, findings } = parsePasses("## Pass not-a-date — distill — ok\n\n- distill: scanned 1 sessions (substantive 1, junk 0), distilled 1, claims 0, none 1, errors 0\n");
    expect(receipts.length).toBe(0);
    expect(findings.length).toBe(1);
    expect(findings[0]).toContain("not-a-date");
  });
});

// ── the loaders (candidate stamps, review queue) ──────────────────────────────

describe("the state loaders", () => {
  it("loads candidate stamps: session_id, session_updated, distilled_at", () => {
    const { stamps, skipped } = loadCandidateStamps(fixtureCandidates());
    expect(skipped).toEqual([]);
    expect(stamps.length).toBe(3);
    const a = stamps.find((s) => s.session_id === "sess-a")!;
    expect(a.file).toBe("claim-sess-a.md");
    expect(a.session_updated).toBe("2026-09-25T00:00:00.000Z");
    expect(a.distilled_at).toBe("2026-10-01T00:00:00.000Z");
  });

  it("names a non-conforming candidate note, never guesses a stamp", () => {
    const dir = mkdtempSync(join(tmpdir(), "brain-health-badcand-"));
    writeFileSync(join(dir, "not-a-candidate.md"), "---\ntype: note\n---\n\nno distill fields\n");
    const { stamps, skipped } = loadCandidateStamps(dir);
    expect(stamps.length).toBe(0);
    expect(skipped.length).toBe(1);
    expect(skipped[0]).toContain("not-a-candidate.md");
  });

  it("reads the review queue's own rendered count", () => {
    const { count, finding } = readReviewQueueCount(fixtureQueue());
    expect(count).toBe(2);
    expect(finding).toBeUndefined();
  });

  it("reads an empty queue as 0; a missing queue is null, never a guess", () => {
    const emptyPath = join(mkdtempSync(join(tmpdir(), "brain-health-emptyq-")), "review-queue.md");
    writeFileSync(emptyPath, renderQueueFile([], { now: CLOCK(), windowDays: 90 }));
    expect(readReviewQueueCount(emptyPath).count).toBe(0);
    const missing = readReviewQueueCount(join(mkdtempSync(join(tmpdir(), "brain-health-noq-")), "review-queue.md"));
    expect(missing.count).toBeNull();
  });
});

// ── the five KPI families over the fixture period — the pinned contract ──────

function fixtureReport() {
  const registryDir = fixtureRegistry();
  const { claims } = loadRegistryClaims(registryDir);
  const { receipts } = parsePasses(fixtureJournal());
  const { stamps } = loadCandidateStamps(fixtureCandidates());
  return computeHealthReport({
    period: PERIOD,
    receipts,
    claims,
    candidates: stamps,
    review_queue: readReviewQueueCount(fixtureQueue()).count,
    pending_tag: 2,
    distill_stamped: fixtureDistillState(),
  });
}

describe("computeHealthReport — fixture-pinned KPIs over 2026-10", () => {
  const report = fixtureReport();

  it("receipts meta: 14 total, 11 in period (failed passes included), per-job counts", () => {
    expect(report.receipts.total).toBe(14);
    expect(report.receipts.in_period).toBe(11);
    expect(report.receipts.by_job).toEqual({
      distill: 4,
      prune: 2,
      promote: 1,
      synthesize: 1,
      "extract-meetings": 2,
      "triage-papers": 1,
    });
  });

  it("family 1 — created 8 (receipts) vs applied 3 (claim history), ratio 0.375", () => {
    expect(report.created_vs_applied.created).toBe(8);
    expect(report.created_vs_applied.created_provenance).toEqual(["2026-10-01: claims 6", "2026-10-02: claims 2"]);
    expect(report.created_vs_applied.applied).toBe(3);
    expect(report.created_vs_applied.applied_provenance).toEqual([
      "best-practice-applied.md: 1 applied event(s)",
      "insight-applied.md: 2 applied event(s)",
    ]);
    expect(report.created_vs_applied.ratio).toBe(0.375);
  });

  it("family 2 — time-to-distill: 2 candidates, median 3.25 days, max 6 days", () => {
    expect(report.time_to_distill.count).toBe(2);
    expect(report.time_to_distill.median_days).toBe(3.25);
    expect(report.time_to_distill.max_days).toBe(6);
  });

  it("family 3 — backlogs: distill 2 (11 substantive − 9 stamped), queue 2, pending-tag 2 (1 acted, 1 skipped)", () => {
    expect(report.backlogs.distill.latest_substantive).toBe(11);
    expect(report.backlogs.distill.stamped).toBe(9);
    expect(report.backlogs.distill.backlog).toBe(2);
    expect(report.backlogs.distill.series).toEqual([
      { date: "2026-10-01", scanned: 30, substantive: 10, distilled: 8, claims: 6, errors: 0 },
      { date: "2026-10-02", scanned: 32, substantive: 11, distilled: 3, claims: 2, errors: 0 },
    ]);
    expect(report.backlogs.review_queue).toBe(2);
    expect(report.backlogs.pending_tag).toEqual({ backlog: 2, acted: 1, skipped: 1 });
  });

  it("family 4 — refutation: 1 refuted vs 1 corroborated in period → rate 0.5; snapshot 1 of 5", () => {
    expect(report.refutation.refuted).toBe(1);
    expect(report.refutation.corroborated).toBe(1);
    expect(report.refutation.rate).toBe(0.5);
    expect(report.refutation.total_claims).toBe(5);
    expect(report.refutation.refuted_claims).toBe(1);
    expect(report.refutation.snapshot_pct).toBeCloseTo(0.2, 10);
  });

  it("family 5 — schema compliance: drift 1 → 4 across the period's prune passes", () => {
    expect(report.schema_compliance.series).toEqual([
      { date: "2026-10-07", fixes: 2, drift: 1 },
      { date: "2026-10-14", fixes: 0, drift: 4 },
    ]);
    expect(report.schema_compliance.latest_drift).toBe(4);
  });

  it("names the ok receipt that left the writer's pinned shape — never a silent skip; a FAILED pass is a fact, not a finding", () => {
    expect(report.findings.some((f) => f.includes("2026-10-03") && f.includes("distill") && f.includes("crashed mid-pass"))).toBe(true);
    expect(report.findings.some((f) => f.includes("2026-10-04"))).toBe(false);
  });

  it("missing substrates are stated, never faked: queue null → finding; stamped null → backlog null", () => {
    const { claims } = loadRegistryClaims(fixtureRegistry());
    const { receipts } = parsePasses(fixtureJournal());
    const bare = computeHealthReport({
      period: PERIOD,
      receipts,
      claims,
      candidates: [],
      review_queue: null,
      pending_tag: null,
      distill_stamped: null,
    });
    expect(bare.backlogs.review_queue).toBeNull();
    expect(bare.backlogs.pending_tag.backlog).toBeNull();
    expect(bare.backlogs.distill.backlog).toBeNull();
    expect(bare.findings.some((f) => f.includes("review queue"))).toBe(true);
  });
});

// ── the brief render — the dated, provenance-carrying publication ──────────────

describe("renderHealthBrief", () => {
  const brief = renderHealthBrief(fixtureReport(), { generated_at: "2026-10-31T00:00:00.000Z" });

  it("is deterministic: same report + same clock → identical bytes", () => {
    expect(renderHealthBrief(fixtureReport(), { generated_at: "2026-10-31T00:00:00.000Z" })).toBe(brief);
  });

  it("carries the period title, the job provenance header, and the measures-never-acts boundary", () => {
    expect(brief).toContain("# Brain health — 2026-10");
    expect(brief).toContain("brain-health");
    expect(brief).toContain("MEASURES, never acts");
  });

  it("renders the pinned numbers with their provenance", () => {
    expect(brief).toContain("created: **8**");
    expect(brief).toContain("applied: **3**");
    expect(brief).toContain("adoption ratio: **37.5%**");
    expect(brief).toContain("2026-10-01: claims 6");
    expect(brief).toContain("median: **3.25 days**");
    expect(brief).toContain("max: **6 days**");
    expect(brief).toContain("distill backlog: **2**");
    expect(brief).toContain("review queue: **2**");
    expect(brief).toContain("pending-tag: **2**");
    expect(brief).toContain("refutation rate: **50%**");
    expect(brief).toContain("1 of 5");
    expect(brief).toContain("drift findings: **1 → 4**");
    expect(brief).toContain("latest drift: **4**");
  });

  it("carries the job id and the issue in its generated-view header (the registry naming)", () => {
    expect(BRAIN_HEALTH_JOB).toBe("brain-health");
    expect(brief).toContain("amicode #1687");
  });
});
