// brain_health_verb.test.ts — the CLI surface of `amico brain-health` (amicode
// #1687, brain flywheel slice 8): the monthly notturno job that renders the
// health report from pass receipts + claim state and publishes it as a dated
// brief. The suite pins the verb's trust boundaries:
//   - the report MEASURES, never acts — decoy substrates (the registry, the
//     candidate area, the review queue, the journal's prior receipts) must
//     survive an apply run byte-identical;
//   - the brief lands in the vault's briefs area, period-keyed (health-YYYY-MM),
//     and is idempotent per period — a re-run overwrites its own brief with
//     identical bytes (same clock), never piles a duplicate;
//   - the notturno chassis gates apply verbatim: the instance deny-list fires
//     before any body work (64), an unknown job id is exit 2, and the receipt
//     (with --jobs) lands on the journal with the pinned outcome shape.
//
// Hermetic: fixture substrates in temp dirs (generated by the real writers —
// the same fixture discipline as brain_health.test.ts), a fake vault root via
// the AMICO_VAULTS_ROOT seam, a fixed clock. Never the live vault, never the
// org registry.
//
// Run: `pnpm --filter @amicode/amico-run test brain_health_verb`
import { describe, it, expect } from "vitest";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { stringify as stringifyYaml } from "yaml";

import { appendSection, renderPass } from "../src/notturno_passes.js";
import { renderClaimNote as renderCandidateNote } from "../src/distill.js";
import { renderQueueFile, type QueueEntry } from "../src/lifecycle.js";
import { writeDistillState, stampDistilled, type DistillState } from "../src/distill.js";
import { brainHealthVerb } from "../src/brain_health_verb.js";
import { SPINE_VERBS } from "../src/verbs.js";

const CLOCK = () => new Date("2026-10-31T00:00:00.000Z");
const OPS = mkdtempSync(join(tmpdir(), "brain-health-verb-ops-"));

// ── the fixture substrate: one temp world, reused per test via a builder ─────

function claimNote(file: string, claim: Record<string, unknown>, dir: string): void {
  writeFileSync(join(dir, file), `---\n${stringifyYaml(claim, { lineWidth: 0 }).trimEnd()}\n---\n\n# ${claim.statement}\n\nfixture claim.\n`);
}

/** One hermetic world: a fake personal vault (registry, candidates, briefs),
 *  a dashboards journal with fixture receipts, a review queue, a distill state
 *  stamp, a meetings tree — every substrate the verb reads. */
function world(opts: { withJobs?: "brain-health" | "other" | "none" } = {}): {
  env: NodeJS.ProcessEnv;
  vault: string;
  dashboards: string;
  journal: string;
  jobs?: string;
  meetings: string;
} {
  const root = mkdtempSync(join(tmpdir(), "brain-health-verb-"));
  const vault = join(root, "vault-aaron");
  mkdirSync(vault, { recursive: true });
  writeFileSync(join(vault, ".amico-vault.toml"), 'kind = "personal"\nname = "vault-aaron"\n');

  const claimsDir = join(vault, "amicode", "claims");
  const candidatesDir = join(claimsDir, "candidates");
  mkdirSync(candidatesDir, { recursive: true });
  claimNote(
    "insight-applied.md",
    {
      type: "insight",
      statement: "two applied events in the period",
      status: "unverified",
      confidence: "medium",
      evidence: ["chat-session/sess-a"],
      applied: 2,
      last_applied: "2026-10-20T00:00:00.000Z",
      history: [
        { date: "2026-08-10T00:00:00.000Z", event: "projected", note: "fixture" },
        { date: "2026-10-04T00:00:00.000Z", event: "applied", note: "applied via recommend-outcome x-gate/12" },
        { date: "2026-10-20T00:00:00.000Z", event: "applied", note: "applied via recommend-outcome t-gate/3" },
      ],
      scope: "personal",
      tags: ["fixture"],
    },
    claimsDir,
  );
  claimNote(
    "insight-refuted.md",
    {
      type: "insight",
      statement: "refuted in the period",
      status: "refuted",
      confidence: "medium",
      evidence: ["chat-session/sess-c"],
      applied: 0,
      last_applied: null,
      history: [
        { date: "2026-08-01T00:00:00.000Z", event: "projected", note: "fixture" },
        { date: "2026-10-03T00:00:00.000Z", event: "refuted", note: "contradicted by run r20261001 (fixture)" },
      ],
      scope: "personal",
      tags: ["fixture"],
    },
    claimsDir,
  );

  const note = (sessionId: string, updatedMs: number, distilledAt: string): string =>
    renderCandidateNote({
      sessionId,
      sessionTitle: `session ${sessionId}`,
      sessionCreatedMs: updatedMs - 86_400_000,
      sessionUpdatedMs: updatedMs,
      sourceDb: "/fixture/chat.db",
      distilledAt,
      claimType: "insight",
      confidence: 0.9,
      evidence: [{ messageId: `msg-${sessionId}`, role: "user", timeCreatedMs: updatedMs, text: "fixture evidence" }],
    });
  writeFileSync(join(candidatesDir, "claim-sess-a.md"), note("sess-a", Date.parse("2026-09-25T00:00:00.000Z"), "2026-10-01T00:00:00.000Z"));
  writeFileSync(join(candidatesDir, "claim-sess-b.md"), note("sess-b", Date.parse("2026-10-01T12:00:00.000Z"), "2026-10-02T00:00:00.000Z"));

  // the distill state stamp: 9 sessions ever distilled
  let state: DistillState = { schema_version: 1, entries: {} };
  for (let i = 0; i < 9; i++) state = stampDistilled(state, `sess-${i}`, "insight", null, "2026-10-02T04:00:00.000Z");
  const statePath = join(OPS, "distill-state.json");
  writeDistillState(statePath, state);

  // the dashboards journal: the period's receipts, through the single writer
  const dashboards = mkdtempSync(join(tmpdir(), "brain-health-verb-dash-"));
  const receipt = (date: string, job: string, outcome: string) =>
    appendSection(dashboards, renderPass({ job, status: "ok", outcome, duration_s: 12, artifacts: [], when: new Date(`${date}T04:00:00.000Z`) }));
  receipt("2026-10-01", "distill", "distill: scanned 30 sessions (substantive 10, junk 20), distilled 8, claims 6, none 2, errors 0");
  receipt("2026-10-02", "distill", "distill: scanned 32 sessions (substantive 11, junk 21), distilled 3, claims 2, none 1, errors 0");
  receipt("2026-10-07", "prune", "prune: 2 fixes applied (2 unambiguous findings), 1 drift findings flagged for a human");
  receipt("2026-10-14", "prune", "prune: 0 fixes applied (0 unambiguous findings), 4 drift findings flagged for a human");
  receipt("2026-10-05", "extract-meetings", "extract-meetings: proposed tags for meeting-a.md (products 1, projects 1, entities 1, types 1, themes 1), 0 named gaps, proposed 1 hopper item(s)");
  receipt("2026-10-12", "extract-meetings", "extract-meetings: skipped meeting-b.md (status tagged)");

  // the review queue: the lifecycle's own rendering, 2 entries
  const queuePath = join(vault, "amicode", "review-queue.md");
  const entry = (file: string, days: number): QueueEntry => ({
    file,
    statement: `stale claim ${file}`,
    type: "insight",
    status: "unverified",
    confidence: "low",
    applied: 0,
    last_applied: null,
    age_days: days,
    reason: `never applied — ${days} days beyond the 90-day window`,
  });
  writeFileSync(queuePath, renderQueueFile([entry("insight-old-a.md", 120), entry("insight-old-b.md", 150)], { now: CLOCK(), windowDays: 90 }));

  // the meetings tree: 2 pending-tag, 1 tagged
  const meetingsRoot = join(root, "meeting-vault");
  const notesDir = join(meetingsRoot, "notes");
  mkdirSync(notesDir, { recursive: true });
  const meeting = (file: string, status: string) =>
    writeFileSync(join(notesDir, file), `---\ntype: meeting\ntitle: ${file}\nstatus: ${status}\nevent_id: ev-${file}\n---\n\nbody.\n`);
  meeting("meeting-a.md", "pending-tag");
  meeting("meeting-b.md", "pending-tag");
  meeting("meeting-c.md", "tagged");

  // the notturno jobs registry for the verb's own receipt
  let jobs: string | undefined;
  if (opts.withJobs !== "none" && opts.withJobs !== undefined) {
    jobs = join(root, "jobs.toml");
    const id = opts.withJobs === "brain-health" ? "brain-health" : "some-other-job";
    writeFileSync(jobs, `[job.${id}]\nworkflow = "notturno-${id}.yml"\ncadence = "0 6 1 * *"\nsurface = "erlich"\nwarrant = "report"\nenabled = false\nrecord = "always"\n`);
  }

  return {
    env: { AMICO_VAULTS_ROOT: root, AMICO_VAULT_DIR: undefined, AMICODE_OPS_DIR: OPS },
    vault,
    dashboards,
    journal: join(dashboards, "scheduled-passes.md"),
    jobs,
    meetings: meetingsRoot,
  };
}

// ── usage + the never-a-guess refusals ────────────────────────────────────────

describe("amico brain-health — usage + refusals", () => {
  it("unknown flag → 64", async () => {
    const w = world();
    const r = await brainHealthVerb(["--bogus"], w.env, { now: CLOCK });
    expect(r.code).toBe(64);
  });

  it("no registry, no mount → 64, never a guess", async () => {
    const bare = mkdtempSync(join(tmpdir(), "brain-health-bare-"));
    const r = await brainHealthVerb(["--dashboards", join(bare, "dash")], { AMICO_VAULTS_ROOT: bare, AMICODE_OPS_DIR: OPS }, { now: CLOCK });
    expect(r.code).toBe(64);
    expect((r.json as { error: string }).error).toContain("--registry");
  });

  it("--dashboards is required (the receipts are the report's primary input)", async () => {
    const w = world();
    const r = await brainHealthVerb([], w.env, { now: CLOCK });
    expect(r.code).toBe(64);
    expect((r.json as { error: string }).error).toContain("--dashboards");
  });

  it("a malformed period is a usage error, never a guessed window", async () => {
    const w = world();
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-13"], w.env, { now: CLOCK });
    expect(r.code).toBe(64);
    expect((r.json as { error: string }).error).toContain("--period");
  });

  it("--jobs with an unknown job id → 2 on the apply path (the registry's membership check, the curation precedent)", async () => {
    const w = world({ withJobs: "other" });
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--jobs", w.jobs!, "--apply"], w.env, { now: CLOCK });
    expect(r.code).toBe(2);
    expect((r.json as { error: string }).error).toContain("brain-health");
  });

  it("a deny-listed registry is refused loudly (64) before any body work", async () => {
    const w = world({ withJobs: "brain-health" });
    const denyList = join(w.vault, "instance-deny-list.toml");
    writeFileSync(denyList, `[[deny]]\npath = "${w.jobs!}"\nreason = "instance config (test fixture)"\n`);
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--jobs", w.jobs!, "--deny-list", denyList], w.env, { now: CLOCK });
    expect(r.code).toBe(64);
    expect((r.json as { error: string }).error).toContain("instance config");
    // the brief was never written — the gate fires before the body
    expect(existsSync(join(w.vault, "briefs"))).toBe(false);
  });

  it("is a registered spine verb named in the job slate", () => {
    const verb = SPINE_VERBS.find((v) => v.name === "brain-health");
    expect(verb).toBeDefined();
    expect(verb!.summary).toContain("brain");
  });
});

// ── the report: dry-run, apply, idempotency, measures-never-acts ──────────────

describe("amico brain-health — the monthly report", () => {
  it("dry-run: report-only — no brief, no receipt, kpis in the JSON", async () => {
    const w = world();
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-10"], w.env, { now: CLOCK });
    expect(r.code).toBe(0);
    const json = r.json as Record<string, unknown>;
    expect(json.dry_run).toBe(true);
    expect(json.period).toBe("2026-10");
    expect((json.kpis as Record<string, unknown>).created_vs_applied).toBeDefined();
    expect(json.brief).toContain("# Brain health — 2026-10");
    expect(json.would_write).toBe(join(w.vault, "briefs", "health-2026-10.md"));
    expect(existsSync(join(w.vault, "briefs"))).toBe(false);
    expect(readFileSync(w.journal, "utf8")).not.toContain("brain-health:");
  });

  it("applies: the brief lands in the briefs area, period-keyed, with the pinned numbers", async () => {
    const w = world();
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-10", "--meetings", w.meetings, "--apply"], w.env, { now: CLOCK });
    expect(r.code).toBe(0);
    const briefPath = join(w.vault, "briefs", "health-2026-10.md");
    expect(existsSync(briefPath)).toBe(true);
    const brief = readFileSync(briefPath, "utf8");
    expect(brief).toContain("# Brain health — 2026-10");
    expect(brief).toContain("created: **8**");
    expect(brief).toContain("applied: **2**");
    expect(brief).toContain("median: **3.25 days**");
    expect(brief).toContain("distill backlog: **2**");
    expect(brief).toContain("review queue: **2**");
    expect(brief).toContain("pending-tag: **2**");
    expect(brief).toContain("refutation rate: **100%**");
    expect(brief).toContain("drift findings: **1 → 4**");
    const json = r.json as Record<string, unknown>;
    expect((json as { wrote: string }).wrote).toBe(briefPath);
  });

  it("defaults the period to the clock's month", async () => {
    const w = world();
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--apply"], w.env, { now: CLOCK });
    expect(r.code).toBe(0);
    expect(existsSync(join(w.vault, "briefs", "health-2026-10.md"))).toBe(true);
  });

  it("is idempotent per period: a re-run (same clock) overwrites its own brief byte-identically — no duplicate briefs", async () => {
    const w = world();
    const argv = ["--dashboards", w.dashboards, "--period", "2026-10", "--apply"];
    await brainHealthVerb(argv, w.env, { now: CLOCK });
    const first = readFileSync(join(w.vault, "briefs", "health-2026-10.md"), "utf8");
    await brainHealthVerb(argv, w.env, { now: CLOCK });
    const briefs = readdirSync(join(w.vault, "briefs"));
    expect(briefs).toEqual(["health-2026-10.md"]);
    expect(readFileSync(join(w.vault, "briefs", "health-2026-10.md"), "utf8")).toBe(first);
    // a different period is a DIFFERENT brief (the trend carrier)
    await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-11", "--apply"], w.env, { now: CLOCK });
    expect(readdirSync(join(w.vault, "briefs")).sort()).toEqual(["health-2026-10.md", "health-2026-11.md"]);
  });

  it("MEASURES, never acts: every substrate survives the apply run byte-identical", async () => {
    const w = world();
    const claimsDir = join(w.vault, "amicode", "claims");
    const before = {
      claim: readFileSync(join(claimsDir, "insight-applied.md"), "utf8"),
      candidate: readFileSync(join(claimsDir, "candidates", "claim-sess-a.md"), "utf8"),
      queue: readFileSync(join(w.vault, "amicode", "review-queue.md"), "utf8"),
      journal: readFileSync(w.journal, "utf8"),
    };
    await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-10", "--apply"], w.env, { now: CLOCK });
    expect(readFileSync(join(claimsDir, "insight-applied.md"), "utf8")).toBe(before.claim);
    expect(readFileSync(join(claimsDir, "candidates", "claim-sess-a.md"), "utf8")).toBe(before.candidate);
    expect(readFileSync(join(w.vault, "amicode", "review-queue.md"), "utf8")).toBe(before.queue);
    // the journal grows ONLY by this pass's own receipt (never rewritten)
    const after = readFileSync(w.journal, "utf8");
    expect(after.startsWith(before.journal)).toBe(true);
  });

  it("the meetings intake is optional: without --meetings the backlog is stated unmeasured, never faked", async () => {
    const w = world();
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-10"], w.env, { now: CLOCK });
    const json = r.json as { kpis: { backlogs: { pending_tag: { backlog: number | null } }; findings: string[] } };
    expect(json.kpis.backlogs.pending_tag.backlog).toBeNull();
    expect(json.kpis.findings.some((f) => f.includes("pending-tag backlog is unmeasured"))).toBe(true);
  });

  it("with --meetings the pending-tag backlog is the meetings vault's own state (2 of 3)", async () => {
    const w = world();
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-10", "--meetings", w.meetings], w.env, { now: CLOCK });
    const json = r.json as { kpis: { backlogs: { pending_tag: { backlog: number | null } } } };
    expect(json.kpis.backlogs.pending_tag.backlog).toBe(2);
  });
});

// ── the receipt (the notturno chassis, the distill precedent) ──────────────────

describe("amico brain-health — the pass receipt", () => {
  it("without --jobs the receipt is honestly not filed", async () => {
    const w = world();
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-10", "--apply"], w.env, { now: CLOCK });
    const json = r.json as { receipt: { filed: boolean } };
    expect(json.receipt.filed).toBe(false);
    expect(readFileSync(w.journal, "utf8")).not.toContain("brain-health:");
  });

  it("with --jobs the apply run files its receipt with the pinned outcome shape", async () => {
    const w = world({ withJobs: "brain-health" });
    const argv = ["--dashboards", w.dashboards, "--period", "2026-10", "--jobs", w.jobs!, "--apply"];
    const r = await brainHealthVerb(argv, w.env, { now: CLOCK });
    expect(r.code).toBe(0);
    const journal = readFileSync(w.journal, "utf8");
    expect(journal).toContain("## Pass 2026-10-31 — brain-health — ok");
    expect(journal).toContain("brain-health: period 2026-10 — receipts 6, claims 2, created 8, applied 2, refuted 1, drift 4 — brief");
    // the receipt is ARTIFACTS-carrying: the brief is the audit pointer
    expect(journal).toContain(join(w.vault, "briefs", "health-2026-10.md"));
    // a re-run parses its own prior receipt cleanly (the journal is append-only;
    // the report reads it back without findings noise)
    const again = await brainHealthVerb(argv, w.env, { now: CLOCK });
    expect(again.code).toBe(0);
    const json = again.json as { kpis: { findings: string[] } };
    expect(json.kpis.findings.some((f) => f.includes("brain-health"))).toBe(false);
  });

  it("dry-run files nothing even with --jobs (report-only)", async () => {
    const w = world({ withJobs: "brain-health" });
    const r = await brainHealthVerb(["--dashboards", w.dashboards, "--period", "2026-10", "--jobs", w.jobs!], w.env, { now: CLOCK });
    expect(r.code).toBe(0);
    const json = r.json as { receipt?: unknown };
    expect(json.receipt).toBeUndefined();
    expect(readFileSync(w.journal, "utf8")).not.toContain("brain-health:");
  });
});
