// SEAM 2 (amicode #699) — regime rules as recommendations: the five-knob
// priors table.
//
// The A1 boundary is the load-bearing invariant: prior VALUES + provenance
// strings ship; the regime-rule ENGINE and VENDOR_PROFILES internals never do.
// The table cites its sources (public-scale arXiv/meeting citations are
// shippable); it does not include or re-implement them — no crossover logic, no
// per-vendor drift scales / trust geometry, no vendor attribution.
//
// Layers (mirroring the calib_chain/rehearsal test shape):
//   1. opencode-plugin/regime_priors.ts — the schema validator, the family
//      scoping, the serving-path composition, and the audit query (F2's
//      sensor), pure logic over a committed data file
//      (opencode-plugin/regime_priors_table.json — generated content,
//      regenerated by an internal-env distiller; that wiring is a named
//      follow-up, not this slice).
//   2. amicode_tools.ts's amicode_recommend — the serving seam: action=query
//      composes these static priors with the existing ledger priors (the tool
//      wrapper is a thin adapter over this core, verified against the real
//      binary, not in vitest).
//
// Outcome events feed the flywheel through the EXISTING mechanics — propose /
// outcome events land in the workspace's events.jsonl via amicode_recommend,
// and the audit reads them back; no new feed exists.
import { describe, it, expect } from "vitest";
import {
  loadRegimePriorsTable,
  validateRegimePriorsTable,
  selectRegimePriors,
  priorProvenanceString,
  platformFamily,
  REGIME_KNOBS,
  CAVEAT_MARKER,
  type PlatformFamily,
} from "../opencode-plugin/regime_priors";

const loaded = loadRegimePriorsTable();

describe("the committed regime-priors table (SEAM 2 schema)", () => {
  it("loads and validates clean, carrying the census stamp + the dynamic-census contract", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    const t = loaded.table;
    // the schema id — the versioned shape the validator pins
    expect(t.schema).toBe("amicode.regime-priors/v1");
    // THE CENSUS STAMP: families + count + date (the profile census the values
    // were distilled from — 2026-08-31, 12 profiles: 4 spin / 4 transmon / 4 atom)
    expect(t.census.date).toBe("2026-08-31");
    expect(t.census.total).toBe(12);
    expect(t.census.families).toEqual({ spin: 4, transmon: 4, atom: 4 });
    // the dynamic-census contract is STATED IN THE SCHEMA: a census change
    // makes the table stale, surfaced by the audit — never a frozen count
    expect(t.dynamic_census_contract).toMatch(/census/i);
    expect(t.dynamic_census_contract).toMatch(/stale/i);
    // the public-scale caveat rides the table (and, per-entry, every provenance)
    expect(t.caveat).toMatch(/do not cite as device data/);
    // the five NAMED knobs are the table's vocabulary (AC1's knob set)
    expect([...REGIME_KNOBS]).toEqual(
      expect.arrayContaining(["tr_frac", "beta", "y_goal", "gls_weighting", "min_contrast"]),
    );
    expect(REGIME_KNOBS.length).toBe(5);
  });

  it("every committed entry's provenance names its profile scope, the census it distilled from, its evidence chain, and the public-scale caveat", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    for (const e of loaded.table.priors) {
      // the profile scope: the platform families the prior covers, named in provenance
      expect(e.provenance.scope.length).toBeGreaterThan(0);
      expect([...e.provenance.scope].sort()).toEqual([...e.families].sort());
      // the census it distilled from (the stamp, verbatim)
      expect(e.provenance.census).toEqual(loaded.table.census);
      // the evidence chain — the campaign fixtures / skills / cards it cites
      expect(e.provenance.sources.length).toBeGreaterThan(0);
      for (const s of e.provenance.sources) expect(s.trim()).not.toBe("");
      // the public-scale caveat riding every entry
      expect(e.provenance.caveat).toContain(CAVEAT_MARKER);
      expect(e.provenance.caveat).toBe(loaded.table.caveat);
      // the knob's label carries the issue's NAMED spelling (β, GLS weighting, …)
      if (e.knob === "beta") expect(e.label).toMatch(/β/);
      if (e.knob === "gls_weighting") expect(e.label).toMatch(/GLS weighting/);
    }
  });
});

describe("validateRegimePriorsTable — a malformed provenance fails", () => {
  const base = (): { table: Record<string, unknown>; priors: Record<string, unknown>[] } => {
    if (!loaded.ok) throw new Error("the committed table must load for the mutation fixtures");
    const table = JSON.parse(JSON.stringify(loaded.table)) as Record<string, unknown>;
    return { table, priors: table.priors as Record<string, unknown>[] };
  };
  const expectProblem = (problems: string[], re: RegExp) =>
    expect(problems.some((p) => re.test(p)), `no problem matches ${re}: got ${JSON.stringify(problems)}`).toBe(true);

  it("fails an entry whose provenance lost the caveat (the caveat rides every entry)", () => {
    const { table, priors } = base();
    delete priors[0].provenance.caveat;
    expectProblem(validateRegimePriorsTable(table), /priors\[0\]\.provenance\.caveat/);
  });

  it("fails an entry whose provenance names a scope that is not its families (scope must be the profile scope)", () => {
    const { table, priors } = base();
    (priors[0].provenance as Record<string, unknown>).scope = ["atom"]; // the spin tr_frac entry claiming atom scope
    expectProblem(validateRegimePriorsTable(table), /priors\[0\]\.provenance\.scope/);
  });

  it("fails an entry whose provenance cites a census that is not the table's stamp (a stale or fabricated census fails)", () => {
    const { table, priors } = base();
    ((priors[0].provenance as Record<string, unknown>).census as Record<string, unknown>).total = 13;
    expectProblem(validateRegimePriorsTable(table), /priors\[0\]\.provenance\.census/);
  });

  it("fails an entry with no evidence chain (empty sources fail)", () => {
    const { table, priors } = base();
    (priors[0].provenance as Record<string, unknown>).sources = [];
    expectProblem(validateRegimePriorsTable(table), /priors\[0\]\.provenance\.sources/);
  });

  it("fails a knob outside the five NAMED knobs, and fails when a family loses knob coverage (regime_rec_priors_live)", () => {
    const { table, priors } = base();
    priors[0].knob = "flavour";
    expectProblem(validateRegimePriorsTable(table), /flavour.*not one of the five NAMED knobs/);
    const t2 = base();
    t2.priors.splice(0, 3); // drop the spin tr_frac entries
    expectProblem(validateRegimePriorsTable(t2.table), /coverage: knob "tr_frac".*"spin"/);
  });
});

// ── AC1: regime_rec_priors_live == 5 — one servable prior per NAMED knob,
// for every census family (not one for the family) ──
describe("selectRegimePriors — the five-knob serving selection", () => {
  it("regime_rec_priors_live == 5: every NAMED knob is servable for every census family, each with value + confidence + its composed provenance", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    for (const family of ["spin", "transmon", "atom"] as PlatformFamily[]) {
      const recs = selectRegimePriors(loaded.table, family);
      // ONE per NAMED knob — exactly the five, no gaps, no dupes
      expect(recs.map((r) => r.param).sort()).toEqual([...REGIME_KNOBS].sort());
      expect(recs.length).toBe(5);
      // the fixture-validated min_contrast is the number 2.5 across families
      const mc = recs.find((r) => r.param === "min_contrast");
      expect(mc?.value).toBe(2.5);
      expect(mc?.confidence).toBe("high");
      // the low-confidence starting points state that honestly
      expect(recs.find((r) => r.param === "tr_frac")?.confidence).toBe("low");
      for (const r of recs) {
        expect(["high", "medium", "low"]).toContain(r.confidence);
        expect(r.value !== undefined && r.value !== "").toBe(true);
      }
    }
  });

  it("params selection filters the knobs (the query path's param projection)", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    const recs = selectRegimePriors(loaded.table, "spin", ["tr_frac", "min_contrast"]);
    expect(recs.map((r) => r.param).sort()).toEqual(["min_contrast", "tr_frac"]);
  });
});

describe("priorProvenanceString — the served provenance names scope + census + sources + caveat", () => {
  it("composes the shippable provenance: profile scope, the census stamp, the evidence chain, and the public-scale caveat riding it", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    const spinTrFrac = loaded.table.priors.find((e) => e.knob === "tr_frac" && e.families.includes("spin"));
    expect(spinTrFrac).toBeDefined();
    if (!spinTrFrac) return;
    const s = priorProvenanceString(spinTrFrac, loaded.table);
    // the profile scope, named
    expect(s).toMatch(/scope: spin\b/);
    // the census it distilled from (families + count + date)
    expect(s).toMatch(/census: 2026-08-31, 12 profiles/);
    expect(s).toMatch(/4 spin \/ 4 transmon \/ 4 atom/);
    // the evidence chain it cites
    expect(s).toMatch(/arXiv:2410\.15590/);
    // the public-scale caveat, riding the served string
    expect(s).toContain(CAVEAT_MARKER);
    // the min_contrast evidence chain cites the Intonatissimo issue numbers (not the code)
    const mc = loaded.table.priors.find((e) => e.knob === "min_contrast");
    expect(mc).toBeDefined();
    if (mc) {
      expect(priorProvenanceString(mc, loaded.table)).toMatch(/Intonatissimo issues #65 \+ #81/);
      expect(priorProvenanceString(mc, loaded.table)).toMatch(/#83 \+ #84/);
    }
  });
});

describe("platformFamily — the coarse platform axis (family keying, never vendor keying)", () => {
  it("maps the interview's platform strings onto the census families", () => {
    expect(platformFamily("transmon")).toBe("transmon");
    expect(platformFamily("rydberg")).toBe("atom");
    expect(platformFamily("neutral-atom Rydberg")).toBe("atom");
    expect(platformFamily("silicon spin qubits")).toBe("spin");
    expect(platformFamily("exchange-coupled spin")).toBe("spin");
  });

  it("honestly returns undefined outside the census families (no prior is served off-census)", () => {
    expect(platformFamily("cavity")).toBeUndefined();
    expect(platformFamily("bosonic")).toBeUndefined();
    expect(platformFamily("fluxonium")).toBeUndefined();
  });
});
