// SEAM 2 (amicode #699) — regime rules as recommendations: the five-knob
// priors table.
//
// The A1 boundary is the load-bearing invariant: prior VALUES + provenance
// strings ship; the regime-rule ENGINE and VENDOR_PROFILES internals never do.
// The table cites its sources (public-scale arXiv/meeting citations are
// shippable); it does not include or re-implement them — no crossover logic, no
// per-vendor drift scales / trust geometry, no vendor attribution.
//
// Layers (mirroring the calib_chain/rehearsal test shape):
//   1. opencode-plugin/regime_priors.ts — the schema validator, the family
//      scoping, the serving-path composition, and the audit query (F2's
//      sensor), pure logic over a committed data file
//      (opencode-plugin/regime_priors_table.json — generated content,
//      regenerated by an internal-env distiller; that wiring is a named
//      follow-up, not this slice).
//   2. amicode_tools.ts's amicode_recommend — the serving seam: action=query
//      composes these static priors with the existing ledger priors (the tool
//      wrapper is a thin adapter over this core, verified against the real
//      binary, not in vitest).
//
// Outcome events feed the flywheel through the EXISTING mechanics — propose /
// outcome events land in the workspace's events.jsonl via amicode_recommend,
// and the audit reads them back; no new feed exists.
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  loadRegimePriorsTable,
  validateRegimePriorsTable,
  selectRegimePriors,
  priorProvenanceString,
  platformFamily,
  serveRecommendations,
  auditRegimePriors,
  auditRegimePriorApplications,
  REGIME_KNOBS,
  CAVEAT_MARKER,
  type PlatformFamily,
} from "../opencode-plugin/regime_priors";
import type { LedgerQueryResult } from "../opencode-plugin/ledger_client";
import { createProblem, appendEvent, writeEntityFiles } from "../opencode-plugin/problems";
import { systemToml } from "../opencode-plugin/entities";

const loaded = loadRegimePriorsTable();

describe("the committed regime-priors table (SEAM 2 schema)", () => {
  it("loads and validates clean, carrying the census stamp + the dynamic-census contract", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    const t = loaded.table;
    // the schema id — the versioned shape the validator pins
    expect(t.schema).toBe("amicode.regime-priors/v1");
    // THE CENSUS STAMP: families + count + date (the profile census the values
    // were distilled from — 2026-08-31, 12 profiles: 4 spin / 4 transmon / 4 atom)
    expect(t.census.date).toBe("2026-08-31");
    expect(t.census.total).toBe(12);
    expect(t.census.families).toEqual({ spin: 4, transmon: 4, atom: 4 });
    // the dynamic-census contract is STATED IN THE SCHEMA: a census change
    // makes the table stale, surfaced by the audit — never a frozen count
    expect(t.dynamic_census_contract).toMatch(/census/i);
    expect(t.dynamic_census_contract).toMatch(/stale/i);
    // the public-scale caveat rides the table (and, per-entry, every provenance)
    expect(t.caveat).toMatch(/do not cite as device data/);
    // the five NAMED knobs are the table's vocabulary (AC1's knob set)
    expect([...REGIME_KNOBS]).toEqual(
      expect.arrayContaining(["tr_frac", "beta", "y_goal", "gls_weighting", "min_contrast"]),
    );
    expect(REGIME_KNOBS.length).toBe(5);
  });

  it("every committed entry's provenance names its profile scope, the census it distilled from, its evidence chain, and the public-scale caveat", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    for (const e of loaded.table.priors) {
      // the profile scope: the platform families the prior covers, named in provenance
      expect(e.provenance.scope.length).toBeGreaterThan(0);
      expect([...e.provenance.scope].sort()).toEqual([...e.families].sort());
      // the census it distilled from (the stamp, verbatim)
      expect(e.provenance.census).toEqual(loaded.table.census);
      // the evidence chain — the campaign fixtures / skills / cards it cites
      expect(e.provenance.sources.length).toBeGreaterThan(0);
      for (const s of e.provenance.sources) expect(s.trim()).not.toBe("");
      // the public-scale caveat riding every entry
      expect(e.provenance.caveat).toContain(CAVEAT_MARKER);
      expect(e.provenance.caveat).toBe(loaded.table.caveat);
      // the knob's label carries the issue's NAMED spelling (β, GLS weighting, …)
      if (e.knob === "beta") expect(e.label).toMatch(/β/);
      if (e.knob === "gls_weighting") expect(e.label).toMatch(/GLS weighting/);
    }
  });
});

describe("validateRegimePriorsTable — a malformed provenance fails", () => {
  const base = (): { table: Record<string, unknown>; priors: Record<string, unknown>[] } => {
    if (!loaded.ok) throw new Error("the committed table must load for the mutation fixtures");
    const table = JSON.parse(JSON.stringify(loaded.table)) as Record<string, unknown>;
    return { table, priors: table.priors as Record<string, unknown>[] };
  };
  const expectProblem = (problems: string[], re: RegExp) =>
    expect(problems.some((p) => re.test(p)), `no problem matches ${re}: got ${JSON.stringify(problems)}`).toBe(true);

  it("fails an entry whose provenance lost the caveat (the caveat rides every entry)", () => {
    const { table, priors } = base();
    delete priors[0].provenance.caveat;
    expectProblem(validateRegimePriorsTable(table), /priors\[0\]\.provenance\.caveat/);
  });

  it("fails an entry whose provenance names a scope that is not its families (scope must be the profile scope)", () => {
    const { table, priors } = base();
    (priors[0].provenance as Record<string, unknown>).scope = ["atom"]; // the spin tr_frac entry claiming atom scope
    expectProblem(validateRegimePriorsTable(table), /priors\[0\]\.provenance\.scope/);
  });

  it("fails an entry whose provenance cites a census that is not the table's stamp (a stale or fabricated census fails)", () => {
    const { table, priors } = base();
    ((priors[0].provenance as Record<string, unknown>).census as Record<string, unknown>).total = 13;
    expectProblem(validateRegimePriorsTable(table), /priors\[0\]\.provenance\.census/);
  });

  it("fails an entry with no evidence chain (empty sources fail)", () => {
    const { table, priors } = base();
    (priors[0].provenance as Record<string, unknown>).sources = [];
    expectProblem(validateRegimePriorsTable(table), /priors\[0\]\.provenance\.sources/);
  });

  it("fails a knob outside the five NAMED knobs, and fails when a family loses knob coverage (regime_rec_priors_live)", () => {
    const { table, priors } = base();
    priors[0].knob = "flavour";
    expectProblem(validateRegimePriorsTable(table), /flavour.*not one of the five NAMED knobs/);
    const t2 = base();
    t2.priors.splice(0, 3); // drop the spin tr_frac entries
    expectProblem(validateRegimePriorsTable(t2.table), /coverage: knob "tr_frac".*"spin"/);
  });
});

// ── AC1: regime_rec_priors_live == 5 — one servable prior per NAMED knob,
// for every census family (not one for the family) ──
describe("selectRegimePriors — the five-knob serving selection", () => {
  it("regime_rec_priors_live == 5: every NAMED knob is servable for every census family, each with value + confidence + its composed provenance", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    for (const family of ["spin", "transmon", "atom"] as PlatformFamily[]) {
      const recs = selectRegimePriors(loaded.table, family);
      // ONE per NAMED knob — exactly the five, no gaps, no dupes
      expect(recs.map((r) => r.param).sort()).toEqual([...REGIME_KNOBS].sort());
      expect(recs.length).toBe(5);
      // the fixture-validated min_contrast is the number 2.5 across families
      const mc = recs.find((r) => r.param === "min_contrast");
      expect(mc?.value).toBe(2.5);
      expect(mc?.confidence).toBe("high");
      // the low-confidence starting points state that honestly
      expect(recs.find((r) => r.param === "tr_frac")?.confidence).toBe("low");
      for (const r of recs) {
        expect(["high", "medium", "low"]).toContain(r.confidence);
        expect(r.value !== undefined && r.value !== "").toBe(true);
      }
    }
  });

  it("params selection filters the knobs (the query path's param projection)", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    const recs = selectRegimePriors(loaded.table, "spin", ["tr_frac", "min_contrast"]);
    expect(recs.map((r) => r.param).sort()).toEqual(["min_contrast", "tr_frac"]);
  });
});

describe("priorProvenanceString — the served provenance names scope + census + sources + caveat", () => {
  it("composes the shippable provenance: profile scope, the census stamp, the evidence chain, and the public-scale caveat riding it", () => {
    expect(loaded.ok).toBe(true);
    if (!loaded.ok) return;
    const spinTrFrac = loaded.table.priors.find((e) => e.knob === "tr_frac" && e.families.includes("spin"));
    expect(spinTrFrac).toBeDefined();
    if (!spinTrFrac) return;
    const s = priorProvenanceString(spinTrFrac, loaded.table);
    // the profile scope, named
    expect(s).toMatch(/scope: spin\b/);
    // the census it distilled from (families + count + date)
    expect(s).toMatch(/census: 2026-08-31, 12 profiles/);
    expect(s).toMatch(/4 spin \/ 4 transmon \/ 4 atom/);
    // the evidence chain it cites
    expect(s).toMatch(/arXiv:2410\.15590/);
    // the public-scale caveat, riding the served string
    expect(s).toContain(CAVEAT_MARKER);
    // the min_contrast evidence chain cites the Intonatissimo issue numbers (not the code)
    const mc = loaded.table.priors.find((e) => e.knob === "min_contrast");
    expect(mc).toBeDefined();
    if (mc) {
      expect(priorProvenanceString(mc, loaded.table)).toMatch(/Intonatissimo issues #65 \+ #81/);
      expect(priorProvenanceString(mc, loaded.table)).toMatch(/#83 \+ #84/);
    }
  });
});

describe("platformFamily — the coarse platform axis (family keying, never vendor keying)", () => {
  it("maps the interview's platform strings onto the census families", () => {
    expect(platformFamily("transmon")).toBe("transmon");
    expect(platformFamily("rydberg")).toBe("atom");
    expect(platformFamily("neutral-atom Rydberg")).toBe("atom");
    expect(platformFamily("silicon spin qubits")).toBe("spin");
    expect(platformFamily("exchange-coupled spin")).toBe("spin");
  });

  it("honestly returns undefined outside the census families (no prior is served off-census)", () => {
    expect(platformFamily("cavity")).toBeUndefined();
    expect(platformFamily("bosonic")).toBeUndefined();
    expect(platformFamily("fluxonium")).toBeUndefined();
  });
});

// ── the serving seam: amicode_recommend action="query" composes these static
// priors (scoped by the session's platform family) with the existing ledger
// priors — the EXISTING mechanics own confidence capping (ledger-sourced caps
// at medium; static priors state their confidence explicitly). ──
describe("serveRecommendations — regime priors composed with ledger priors", () => {
  const ledger = (): LedgerQueryResult => ({
    key: "primary",
    structure_hash: "sh-x",
    total: 3,
    verified: 2,
    params: {
      N: { value: 50, iqr: [50, 50], n: 3 },
      max_iter: { value: 60, iqr: [60, 80], n: 3 },
    },
    provenance: "3 runs, 2 verified",
    confidence: "high",
  });
  const table = () => loaded; // the committed table's LoadResult (ok: true)

  it("serves the five regime priors (platform-scoped) ALONGSIDE the ledger priors, the ledger still capped at medium", () => {
    const served = serveRecommendations({ table: table(), platform: "transmon", ledger: ledger() });
    const regime = served.recommendations.filter((r) => r.origin === "regime");
    const fromLedger = served.recommendations.filter((r) => r.origin === "ledger");
    // the five NAMED knobs, scoped to the session's platform family
    expect(regime.map((r) => r.param).sort()).toEqual([...REGIME_KNOBS].sort());
    for (const r of regime) {
      expect(r.provenance).toMatch(/^scope: /);
      expect(r.provenance).toContain(CAVEAT_MARKER);
    }
    // the ledger priors ride along, their confidence CAPPED at medium (the
    // existing interim guard — high on the wire, medium at the surface)
    expect(fromLedger.map((r) => r.param).sort()).toEqual(["N", "max_iter"]);
    expect(fromLedger.every((r) => r.confidence === "medium")).toBe(true);
    // the static priors state their own confidence explicitly (never capped up)
    expect(regime.find((r) => r.param === "min_contrast")?.confidence).toBe("high");
  });

  it("serves the regime priors even without ledger history (the static priors are not run-gated)", () => {
    const served = serveRecommendations({ table: table(), platform: "spin" });
    expect(served.recommendations.filter((r) => r.origin === "regime").length).toBe(5);
    expect(served.regimeNote).toBeUndefined();
  });

  it("honestly notes absence for an unmapped platform (no nearest-guess prior)", () => {
    const served = serveRecommendations({ table: table(), platform: "cavity", ledger: ledger() });
    expect(served.recommendations.filter((r) => r.origin === "regime")).toEqual([]);
    expect(served.regimeNote).toMatch(/no regime priors for platform "cavity"/);
    expect(served.recommendations.filter((r) => r.origin === "ledger").length).toBe(2);
  });

  it("projects the params selection onto BOTH sources", () => {
    const served = serveRecommendations({
      table: table(),
      platform: "transmon",
      ledger: ledger(),
      params: ["min_contrast", "N"],
    });
    expect(served.recommendations.map((r) => r.param).sort()).toEqual(["N", "min_contrast"]);
  });

  it("degrades honestly on an invalid table (the ledger still serves; the regime notes the failure)", () => {
    const served = serveRecommendations({
      table: { ok: false, problems: ["schema: expected amicode.regime-priors/v0"] },
      platform: "transmon",
      ledger: ledger(),
    });
    expect(served.recommendations.filter((r) => r.origin === "ledger").length).toBe(2);
    expect(served.recommendations.filter((r) => r.origin === "regime")).toEqual([]);
    expect(served.regimeNote).toMatch(/regime priors table/);
  });
});

// ── F2's mechanical sensor: the audit query over prior-application events.
// A prior applied OUTSIDE its profile scope without the caveat surfaced → the
// audit FAILS; the WITH-caveat case passes (the caveat is the point).
// Prior applications ride the EXISTING mechanics: amico_recommend propose
// events carrying a provenance entry with source "regime-prior" and the served
// provenance string as its note. ──
describe("auditRegimePriors — the off-profile sensor", () => {
  const table = () => {
    if (!loaded.ok) throw new Error("the committed table must load");
    return loaded.table;
  };
  // a served provenance string, as it rides a propose event's regime-prior entry
  const servedNote = (knob: string, family: PlatformFamily): string => {
    const recs = selectRegimePriors(table(), family);
    return recs.find((r) => r.param === knob)?.provenance ?? "";
  };
  const application = (seq: number, key: string, note: string, provenanceSource = "regime-prior") => ({
    seq,
    key,
    param: key.split("/")[1] ?? "?",
    provenance: [{ source: provenanceSource, ref: "regime_priors_table.json", note }],
  });

  it("passes an on-scope application (spin prior, spin session, caveat present)", () => {
    const note = servedNote("tr_frac", "spin");
    const res = auditRegimePriors({
      table: table(),
      family: "spin",
      applications: [application(1, "calibrate/tr_frac", note)],
    });
    expect(res.ok).toBe(true);
    expect(res.violations).toEqual([]);
    expect(res.audited).toBe(1);
  });

  it("FAILS a prior applied outside its profile scope WITHOUT the caveat surfaced (the violation fixture)", () => {
    // a spin-scoped prior (scope: spin) applied in a transmon session, with
    // the caveat STRIPPED from the provenance string — the misleading case
    const stripped = servedNote("tr_frac", "spin").replace(/caveat: [^;]+;?/, "");
    expect(stripped).not.toContain(CAVEAT_MARKER);
    const res = auditRegimePriors({
      table: table(),
      family: "transmon",
      applications: [application(1, "calibrate/tr_frac", stripped)],
    });
    expect(res.ok).toBe(false);
    expect(res.violations.length).toBe(1);
    expect(res.violations[0].seq).toBe(1);
    expect(res.violations[0].reason).toMatch(/outside its profile scope/);
    expect(res.violations[0].reason).toMatch(/caveat/);
  });

  it("PASSES the same off-scope application WITH the caveat surfaced (the caveat is the point)", () => {
    const note = servedNote("tr_frac", "spin"); // scope: spin — applied in an atom session
    const res = auditRegimePriors({
      table: table(),
      family: "atom",
      applications: [application(1, "calibrate/tr_frac", note)],
    });
    expect(res.ok).toBe(true);
    expect(res.violations).toEqual([]);
  });

  it("fails a regime-prior application whose provenance does not name its scope (unverifiable scope)", () => {
    const noteless = "a hand-written prior with no scope marker and no caveat";
    const res = auditRegimePriors({
      table: table(),
      family: "spin",
      applications: [application(2, "calibrate/beta", noteless)],
    });
    expect(res.ok).toBe(false);
    expect(res.violations[0].reason).toMatch(/does not name its profile scope/);
  });

  it("ignores non-regime recommendations (only regime-prior applications are audited)", () => {
    const res = auditRegimePriors({
      table: table(),
      family: "spin",
      applications: [application(3, "solve/N", "ledger prior", "ledger")],
    });
    expect(res.ok).toBe(true);
    expect(res.audited).toBe(0);
  });

  it("surfaces census staleness when the current census differs from the table's stamp (the dynamic-census contract)", () => {
    const res = auditRegimePriors({
      table: table(),
      family: "spin",
      applications: [],
      currentCensus: { date: "2026-09-15", total: 13, families: { spin: 5, transmon: 4, atom: 4 } },
    });
    expect(res.ok).toBe(false);
    expect(res.stale).toBeDefined();
    expect(res.stale?.stamped.total).toBe(12);
    expect(res.stale?.current.total).toBe(13);
  });

  it("passes with a matching current census (the stamp is live)", () => {
    const res = auditRegimePriors({
      table: table(),
      family: "spin",
      applications: [],
      currentCensus: { date: "2026-08-31", total: 12, families: { spin: 4, transmon: 4, atom: 4 } },
    });
    expect(res.ok).toBe(true);
    expect(res.stale).toBeUndefined();
  });
});

// ── the workspace wrapper — the audit query over a real problem workspace:
// prior applications are the propose/outcome events the EXISTING amico_recommend
// mechanics append to events.jsonl (the flywheel's input side, no new feed). ──
describe("auditRegimePriorApplications — the workspace audit", () => {
  let problemsRoot: string;
  const prevProblems = process.env.AMICODE_PROBLEMS_DIR;

  beforeEach(() => {
    problemsRoot = mkdtempSync(join(tmpdir(), "regime-priors-audit-"));
    process.env.AMICODE_PROBLEMS_DIR = problemsRoot;
  });
  afterEach(() => {
    if (prevProblems === undefined) delete process.env.AMICODE_PROBLEMS_DIR;
    else process.env.AMICODE_PROBLEMS_DIR = prevProblems;
    rmSync(problemsRoot, { recursive: true, force: true });
  });

  const SPIN_SYSTEM = { platform: "silicon spin qubits", levels: 3, params: {} };

  function stageWorkspace(platform: Record<string, unknown>): string {
    const meta = createProblem("audit fixture");
    writeEntityFiles(meta.slug, "system", systemToml(platform as never), JSON.stringify(platform) + "\n");
    return meta.slug;
  }

  /** The propose event amico_recommend would append for a served regime prior. */
  function proposeRegimePrior(slug: string, note: string, stage = "calibrate", param = "tr_frac", seq?: number) {
    return appendEvent(slug, {
      entity: "recommendation",
      action: "proposed",
      diff: {
        key: `${stage}/${param}`,
        stage,
        param,
        value: "0.05-0.1",
        confidence: "low",
        provenance: [{ source: "regime-prior", ref: `regime_priors_table.json#${param}@spin`, note }],
      },
      source: { tool: "amicode_recommend", stage },
    });
  }

  it("audits a clean workspace: on-scope application + its outcome pair (the existing flywheel feed) passes", () => {
    const slug = stageWorkspace(SPIN_SYSTEM);
    const note = selectRegimePriors((loaded.ok ? loaded.table : undefined)!, "spin").find((r) => r.param === "tr_frac")!
      .provenance;
    const seq = proposeRegimePrior(slug, note);
    appendEvent(slug, {
      entity: "recommendation",
      action: "outcome",
      diff: { key: "calibrate/tr_frac", stage: "calibrate", param: "tr_frac", outcome: "accepted", applied_value: "0.05-0.1" },
      source: { tool: "amicode_recommend", stage: "calibrate" },
    });
    const res = auditRegimePriorApplications(slug);
    expect(res.ok).toBe(true);
    expect(res.audited).toBe(1);
    expect(res.family).toBe("spin");
    expect(res.platform).toBe("silicon spin qubits");
    expect(res.applied).toBe(1); // the outcome pair — the flywheel's input side
  });

  it("FAILS on a violation fixture: an off-scope prior applied without the caveat surfaced", () => {
    const slug = stageWorkspace(SPIN_SYSTEM);
    // a transmon-scoped prior (scope: transmon) proposed into a spin workspace,
    // caveat stripped — the misleading case F2 exists to catch
    const note = selectRegimePriors((loaded.ok ? loaded.table : undefined)!, "transmon").find((r) => r.param === "tr_frac")!
      .provenance.replace(/caveat: [^;]+;?/, "");
    const seq = proposeRegimePrior(slug, note);
    const res = auditRegimePriorApplications(slug);
    expect(res.ok).toBe(false);
    expect(res.violations.length).toBe(1);
    expect(res.violations[0].seq).toBe(seq);
    expect(res.violations[0].reason).toMatch(/outside its profile scope/);
  });

  it("degrades honestly with no system recorded (nothing to scope against — the caveat alone can save an application)", () => {
    const meta = createProblem("no system workspace");
    const note = selectRegimePriors((loaded.ok ? loaded.table : undefined)!, "spin").find((r) => r.param === "tr_frac")!
      .provenance;
    proposeRegimePrior(meta.slug, note);
    const res = auditRegimePriorApplications(meta.slug);
    expect(res.ok).toBe(true); // the caveat rides the served provenance
    expect(res.family).toBeUndefined();
    expect(res.platform).toBeUndefined();
  });

  it("surfaces census staleness through the workspace wrapper (a changed census makes the table stale — the audit reports it)", () => {
    const slug = stageWorkspace(SPIN_SYSTEM);
    const res = auditRegimePriorApplications(slug, {
      currentCensus: { date: "2026-09-15", total: 13, families: { spin: 5, transmon: 4, atom: 4 } },
    });
    expect(res.ok).toBe(false); // stale census surfaced
    expect(res.stale?.stamped.total).toBe(12);
    expect(res.stale?.current.total).toBe(13);
  });

  it("fails honestly when the table itself cannot load (a broken sensor never silently passes)", () => {
    const slug = stageWorkspace(SPIN_SYSTEM);
    // The wrapper loads the committed file; simulate the unloadable-table path
    // by pointing the loader at an empty dir through the exported path seam is
    // not possible — instead pin the SHAPE: an ok:false with tableProblems is
    // what an unloadable table yields (unit-pinned in the pure-core tests).
    const res = auditRegimePriorApplications(slug);
    expect(res.tableProblems).toBeUndefined(); // the committed table loads
    expect(res.ok).toBe(true);
  });
});

// ── AC4: attribution-free in the A1 sense — prior VALUES + provenance strings
// ship; no crossover logic, no profile internals, no vendor attribution. The
// profiles' sources are public-scale arXiv/meeting citations, which ARE
// shippable — the leak guard draws the line mechanically: no census-vendor
// names anywhere in the shipped table, no profile-internal magnitude fields
// (per-vendor drift scales, trust geometry), family-level scoping only. ──
describe("the committed table — the A1 leak guard", () => {
  const raw = readFileSync(join(__dirname, "..", "opencode-plugin", "regime_priors_table.json"), "utf8");

  it("carries no vendor attribution (the census vendors are named NOWHERE — family keying only)", () => {
    const vendors = [
      "diraq", "hrl", "intel", "groove",
      "google", "ibm", "iqm", "rigetti",
      "quera", "pasqal", "atomcomputing", "atom computing", "logiqal",
    ];
    const lowered = raw.toLowerCase();
    for (const v of vendors) expect(lowered, `vendor "${v}" must not appear in the shipped table`).not.toContain(v);
  });

  it("carries no profile internals — no drift-scale / trust-geometry / crossover fields, only the five-knob values + their citations", () => {
    const table = JSON.parse(raw) as Record<string, unknown>;
    // the top-level shape is the schema, nothing else
    expect(Object.keys(table).sort()).toEqual(["caveat", "census", "dynamic_census_contract", "priors", "schema"]);
    const walk = (node: unknown): void => {
      if (Array.isArray(node)) {
        node.forEach(walk);
        return;
      }
      if (typeof node !== "object" || node === null) return;
      for (const [k, v] of Object.entries(node)) {
        expect(k, `profile-internal field "${k}" must not ship`).not.toMatch(/drift|trust|geometry|crossover|vendor/);
        walk(v);
      }
    };
    walk(table);
    // every entry keys on a NAMED knob with family-level scope — the
    // profile-scope families are the platform families, never vendors
    for (const e of table.priors as Record<string, unknown>[]) {
      expect(REGIME_KNOBS).toContain(e.knob);
      expect((e.families as string[]).every((f) => ["spin", "transmon", "atom"].includes(f))).toBe(true);
    }
  });
});
